import Head from "next/head";

const About = () => {
  return (
    <div>
      <Head>
        <title>Webdev Newz | About</title>
        <meta
          name="description"
          content="Generated by using create next app . this project has developed by kathiravan vellaisamy"
        />
        <meta
          name="keywords"
          content="programming,web development,frontend,backend,server side rendering"
        />
      </Head>
      <h1>About Me</h1>
      <p>He is a MERN Stack developer</p>
    </div>
  );
};

export default About;
